### ISSUE TITLE
Add native binary build via Graalvm + Jreleases

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/migtool#12]
To make the tool easier to use it should be compiled via Graal native build and uploaded to the GitHub release page using [Jreleaser](https://jreleaser.org/). 

The build script used by [tower-cli](https://github.com/seqeralabs/tower-cli) can be used as a template

**Comment by pditommaso** [comment]
Not sure to understand, version hardcode where in the binary file name?

**Comment by jorgeaguileraseqera** [comment]
if I'm not wrong every time we want to release a new version we change the VERSION file and commit it

whit these tools we can avoid this commit. Reckon (for example) works inspecting git log and when we run the `release` task it takes the last tag, for example, `v1.0.1`, and change the version property on the fly to `v1.0.2` and also it can tag the repo using this value

**Comment by pditommaso** [comment]
Looks nice, and it determines what's next version? e.g. `1.0.2` or `1.1.0` ?

**Comment by jorgeaguileraseqera** [comment]
yes. Reckon for example can be executed with 2 params: scope and stage

scope can be major, minor, patch
stage can be a list of strings for example 'milestone', 'rc', 'final'

when you're ready to release a new version you set these attributes and reckon decides which version applies. 

For example, if the last version was `1.0.2` 

scope=patch, stage=rc ==> version `1.0.3-rc.1`
scope=minor, stage=final ==> version `1.1.0`
scope=major, stage=final ==> version `2.0.0`

all of this without the need to change/commit any files, you can use, for example, github actions parameters to run the release process passing `scope` and `stage` values

**Comment by pditommaso** [comment]
I'm missing where scope and stage are specified?

**Comment by pditommaso** [comment]
Overengineering! 😄

**Comment by pditommaso** [comment]
Ok, seems so 

http://github.com/seqeralabs/migtool/blob/fcf7ad44382f2f018ae48508a052a19ca333e8b8/.github/workflows/build.yml#L91-L95
